[package]
name = "ipv4peersrs"
version = "0.1.0"
authors = ["Rujak Ironhammer <sirrujak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
